<!DOCTYPE html>
<!-- saved from url=(0022)http://localhost:5419/ -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>UFCProj</title>
<style class="anchorjs"></style><style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="./ufcproj_files/clipboard.min.js.download"></script>
<script src="./ufcproj_files/quarto.js.download"></script>
<script src="./ufcproj_files/popper.min.js.download"></script>
<script src="./ufcproj_files/tippy.umd.min.js.download"></script>
<script src="./ufcproj_files/anchor.min.js.download"></script>
<link href="./ufcproj_files/tippy.css" rel="stylesheet">
<link href="./ufcproj_files/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="./ufcproj_files/bootstrap.min.js.download"></script>
<link href="./ufcproj_files/bootstrap-icons.css" rel="stylesheet">
<link href="./ufcproj_files/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<style>.ansi-display{font-family:monospace;white-space:pre-wrap;--ansiBlack: #000000;--ansiRed: #cd3131;--ansiGreen: #00BC00;--ansiYellow: #949800;--ansiBlue: #0451a5;--ansiMagenta: #bc05bc;--ansiCyan: #0598bc;--ansiWhite: #555555;--ansiBrightBlack: #666666;--ansiBrightRed: #cd3131;--ansiBrightGreen: #14CE14;--ansiBrightYellow: #b5ba00;--ansiBrightBlue: #0451a5;--ansiBrightMagenta: #bc05bc;--ansiBrightCyan: #0598bc;--ansiBrightWhite: #a5a5a5}.dark-mode .ansi-display{--ansiBlack: #000000;--ansiRed: #cd3131;--ansiGreen: #0DBC79;--ansiYellow: #e5e510;--ansiBlue: #2472c8;--ansiMagenta: #bc3fbc;--ansiCyan: #11a8cd;--ansiWhite: #e5e5e5;--ansiBrightBlack: #666666;--ansiBrightRed: #f14c4c;--ansiBrightGreen: #23d18b;--ansiBrightYellow: #f5f543;--ansiBrightBlue: #3b8eea;--ansiBrightMagenta: #d670d6;--ansiBrightCyan: #29b8db;--ansiBrightWhite: #e5e5e5}@keyframes ansi-displaly-run-blink{50%{opacity:0}}.fui-FluentProvider h2{border-bottom:none;padding-bottom:0}</style></head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">UFCProj</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="project-goal" class="level1">
<h1>Project Goal</h1>
<p>To predict winners of UFC fights from available data (or data calculated from available data).</p>
</section>
<section id="source-data" class="level1">
<h1>Source Data</h1>
<p>Kaggle Datasets: <a href="https://www.kaggle.com/datasets/remypereira/mma-dataset-2023-ufc">Link</a></p>
<p>There are four datasets linked through foreign keys, so the first step was to wrangle the data from each dataset into one usable source. To do this, we used alteryx:</p>
<section id="joining-datasets" class="level2">
<h2 class="anchored" data-anchor-id="joining-datasets">Joining Datasets<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#joining-datasets" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p><img src="./ufcproj_files/UFC Joining.png" class="img-fluid"></p>
<p>Here, datasets were joined on keys, and each row shows a fight. To distinguish fighters in the same fight, an arbitrary prefix was assigned to the fighters characteristics, being l and r (for left and right). The reason for this is that if we analyzed fighters in the same fight, the predictor variables would have very high multicollinearity. More on this later.</p>
</section>
<section id="calculating-predictor-variables" class="level2">
<h2 class="anchored" data-anchor-id="calculating-predictor-variables">Calculating Predictor Variables<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#calculating-predictor-variables" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p><img src="./ufcproj_files/Formulating UFC.png" class="img-fluid"></p>
<p>Here, we calculated new columns to be used during analysis. These columns were things like seniority (how much older a fighter was than the other. For example, the l_seniority column records how much older the left fighter was than the right fighter. A value of 4 in that column would mean the left fighter was 4 years older than the right fighter). Note - when building models later on, l_seniority and r_seniority would never be in the same model because they are opposites. Other variables were things like weight difference, reach difference, win loss ratio difference, etc.</p>
</section>
<section id="more-calculated-predictors" class="level2">
<h2 class="anchored" data-anchor-id="more-calculated-predictors">More Calculated Predictors<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#more-calculated-predictors" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p><img src="./ufcproj_files/CalcCol.png" class="img-fluid"></p>
<p>These columns were added later on in the time frame of the project, just to try out some more predictors. These included win streaks the fighters were on before the fight, TKOs received (how many times they’d been knocked out before the fight - cumulative), and how long it had been since their last fight (rustiness). Spoiler - win streak was the only relevant variable from these calculations found during model testing</p>
</section>
<section id="differences-of-new-columns" class="level2">
<h2 class="anchored" data-anchor-id="differences-of-new-columns">Differences of New Columns<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#differences-of-new-columns" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p><img src="./ufcproj_files/newColFormulations.png" class="img-fluid"></p>
<p>These last formulations were just calculating differences between the new columns like win streak, so a value of 4 in the l_win_streak_dif column would mean that the left fighter is on a win streak four higher than the right fighter. Our thought process was that this could translate to confidence in a fight.</p>
</section>
</section>
<section id="loading-data-and-summary-stats" class="level1">
<h1>Loading Data and Summary Stats</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="http://localhost:5419/#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="http://localhost:5419/#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-3"><a href="http://localhost:5419/#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rattle)</span>
<span id="cb1-4"><a href="http://localhost:5419/#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="http://localhost:5419/#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb1-6"><a href="http://localhost:5419/#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="http://localhost:5419/#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/lwhite01/Data/main/finalFighter.csv'</span>)</span>
<span id="cb2-2"><a href="http://localhost:5419/#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       l_FullName     r_FullName      w_FullName  FightDate l_win r_win
1   Spike Carlyle     Aalon Cruz   Spike Carlyle 2020-02-29     1     0
2 Andrei Arlovski    Aaron Brink Andrei Arlovski 2000-11-17     1     0
3      Matt Hobar Aaron Phillips      Matt Hobar 2014-08-23     1     0
4  Gaston Bolanos Aaron Phillips  Gaston Bolanos 2023-04-15     1     0
5   Robbie Lawler    Aaron Riley   Robbie Lawler 2002-05-10     1     0
6  Spencer Fisher    Aaron Riley  Spencer Fisher 2006-01-16     1     0
  l_seniority r_seniority l_w.l_ratio r_w.l_ratio l_height_dif_cm
1          -4           4    3.000000    2.000000      -10.160000
2          -5           5    1.545455    1.000000        0.000000
3           2          -2    3.000000    2.400000        2.540009
4          -3           3    2.333333    2.400000       -5.080002
5          -1           1    1.875000    2.142857        7.619995
6           4          -4    2.666667    2.142857       -2.540009
  r_height_dif_cm l_weight_dif_lb r_weight_dif_lb l_reach_dif_cm r_reach_dif_cm
1       10.160000               0               0     -17.780000      17.780000
2        0.000000              35             -35       2.580002      -2.580002
3       -2.540009               0               0      -2.539993       2.539993
4        5.080002               0               0      -5.080002       5.080002
5       -7.619995              15             -15      12.700010     -12.700010
6        2.540009               0               0      -2.539993       2.539993
  l_total_fights r_total_fights l_total_fights_dif r_total_fights_dif
1             12             12                  0                  0
2             56             52                  4                 -4
3             12             17                 -5                  5
4             10             17                 -7                  7
5             46             44                  2                 -2
6             33             44                -11                 11
  l_win_difference r_win_difference l_WinStreak r_WinStreak l_TKOReceived
1       1.00000000      -1.00000000           0           0             0
2       0.54545450      -0.54545450           0           0             0
3       0.59999990      -0.59999990           0           0             1
4      -0.06666684       0.06666684           0           0             0
5      -0.26785707       0.26785707           0           0             0
6       0.52380967      -0.52380967           0           0             0
  r_TKOReceived l_WinStreak_dif r_WinStreak_dif l_TKOReceived_dif
1             0               0               0                 0
2             0               0               0                 0
3             0               0               0                 1
4             0               0               0                 0
5             0               0               0                 0
6             0               0               0                 0
  r_TKOReceived_dif l_rust_ring r_rust_ring l_rustRing_dif r_rustRing_dif
1                 0           0           0              0              0
2                 0           0           0              0              0
3                -1          84           0             84            -84
4                 0           0        3157          -3157           3157
5                 0           0           0              0              0
6                 0           0        1347          -1347           1347</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="http://localhost:5419/#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  l_FullName         r_FullName         w_FullName         FightDate        
 Length:7186        Length:7186        Length:7186        Length:7186       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
     l_win            r_win         l_seniority        r_seniority      
 Min.   :0.0000   Min.   :0.0000   Min.   :-23.0000   Min.   :-17.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.: -3.0000   1st Qu.: -4.0000  
 Median :1.0000   Median :0.0000   Median :  0.0000   Median :  0.0000  
 Mean   :0.5014   Mean   :0.4986   Mean   :  0.0892   Mean   : -0.0892  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:  4.0000   3rd Qu.:  3.0000  
 Max.   :1.0000   Max.   :1.0000   Max.   : 17.0000   Max.   : 23.0000  
                                   NA's   :213        NA's   :213       
  l_w.l_ratio      r_w.l_ratio     l_height_dif_cm    r_height_dif_cm   
 Min.   : 0.000   Min.   : 0.000   Min.   :-33.0200   Min.   :-22.8600  
 1st Qu.: 1.818   1st Qu.: 1.833   1st Qu.: -5.0800   1st Qu.: -5.0800  
 Median : 2.333   Median : 2.385   Median :  0.0000   Median :  0.0000  
 Mean   : 3.049   Mean   : 3.037   Mean   : -0.2411   Mean   :  0.2411  
 3rd Qu.: 3.333   3rd Qu.: 3.333   3rd Qu.:  5.0800   3rd Qu.:  5.0800  
 Max.   :29.000   Max.   :29.000   Max.   : 22.8600   Max.   : 33.0200  
                                   NA's   :22         NA's   :22        
 l_weight_dif_lb     r_weight_dif_lb     l_reach_dif_cm     
 Min.   :-570.0000   Min.   :-115.0000   Min.   :-33.01999  
 1st Qu.:   0.0000   1st Qu.:   0.0000   1st Qu.: -5.08000  
 Median :   0.0000   Median :   0.0000   Median :  0.00000  
 Mean   :  -0.7217   Mean   :   0.7217   Mean   : -0.08277  
 3rd Qu.:   0.0000   3rd Qu.:   0.0000   3rd Qu.:  5.08000  
 Max.   : 115.0000   Max.   : 570.0000   Max.   : 32.00000  
 NA's   :20          NA's   :20                             
 r_reach_dif_cm      l_total_fights   r_total_fights   l_total_fights_dif 
 Min.   :-32.00000   Min.   :  1.00   Min.   :  1.00   Min.   :-295.0000  
 1st Qu.: -5.08000   1st Qu.: 17.00   1st Qu.: 17.00   1st Qu.:  -8.0000  
 Median :  0.00000   Median : 24.00   Median : 23.00   Median :   0.0000  
 Mean   :  0.08277   Mean   : 25.98   Mean   : 25.69   Mean   :   0.2844  
 3rd Qu.:  5.08000   3rd Qu.: 32.00   3rd Qu.: 32.00   3rd Qu.:   8.0000  
 Max.   : 33.01999   Max.   :306.00   Max.   :306.00   Max.   : 288.0000  
                                                                          
 r_total_fights_dif  l_win_difference    r_win_difference     l_WinStreak     
 Min.   :-288.0000   Min.   :-27.84211   Min.   :-27.20000   Min.   : 0.0000  
 1st Qu.:  -8.0000   1st Qu.: -0.98574   1st Qu.: -1.00000   1st Qu.: 0.0000  
 Median :   0.0000   Median :  0.00000   Median :  0.00000   Median : 0.0000  
 Mean   :  -0.2844   Mean   :  0.01205   Mean   : -0.01205   Mean   : 0.8247  
 3rd Qu.:   8.0000   3rd Qu.:  1.00000   3rd Qu.:  0.98574   3rd Qu.: 1.0000  
 Max.   : 295.0000   Max.   : 27.20000   Max.   : 27.84211   Max.   :10.0000  
                                                                              
  r_WinStreak      l_TKOReceived    r_TKOReceived    l_WinStreak_dif    
 Min.   : 0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :-12.00000  
 1st Qu.: 0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.: -1.00000  
 Median : 0.0000   Median :0.0000   Median :0.0000   Median :  0.00000  
 Mean   : 0.8411   Mean   :0.3781   Mean   :0.3586   Mean   : -0.01642  
 3rd Qu.: 1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:  1.00000  
 Max.   :14.0000   Max.   :8.0000   Max.   :6.0000   Max.   :  9.00000  
                                                                        
 r_WinStreak_dif    l_TKOReceived_dif  r_TKOReceived_dif   l_rust_ring    
 Min.   :-9.00000   Min.   :-6.00000   Min.   :-7.00000   Min.   :   0.0  
 1st Qu.:-1.00000   1st Qu.: 0.00000   1st Qu.: 0.00000   1st Qu.:   0.0  
 Median : 0.00000   Median : 0.00000   Median : 0.00000   Median : 154.0  
 Mean   : 0.01642   Mean   : 0.01948   Mean   :-0.01948   Mean   : 232.6  
 3rd Qu.: 1.00000   3rd Qu.: 0.00000   3rd Qu.: 0.00000   3rd Qu.: 293.0  
 Max.   :12.00000   Max.   : 7.00000   Max.   : 6.00000   Max.   :4180.0  
                                                                          
  r_rust_ring     l_rustRing_dif      r_rustRing_dif     
 Min.   :   0.0   Min.   :-4887.000   Min.   :-4047.000  
 1st Qu.:   0.0   1st Qu.: -147.000   1st Qu.: -147.000  
 Median : 154.0   Median :    0.000   Median :    0.000  
 Mean   : 235.7   Mean   :   -3.173   Mean   :    3.173  
 3rd Qu.: 294.0   3rd Qu.:  147.000   3rd Qu.:  147.000  
 Max.   :5181.0   Max.   : 4047.000   Max.   : 4887.000  
                                                         </code></pre>
</div>
</div>
<section id="structure" class="level2">
<h2 class="anchored" data-anchor-id="structure">Structure<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#structure" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>l_win and r_win are binary variables showing who won the fight (if l_win = 1, the left fighter won). Everything else is knowledge of the fighters from before the fight. The approach of all the models (regardless if LDA or logistic regression) is to use the variables calculated in alteryx to predict a win or loss.</p>
<p>Left and right are done separately. Later on, you’ll see that confidence intervals are set to increase precision. A benefit of breaking the data into left and right fighters for left and right models is that you can double check that both models are saying the same thing.</p>
</section>
<section id="outliers" class="level2">
<h2 class="anchored" data-anchor-id="outliers">Outliers<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#outliers" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>Refer to l_weight_dif_lb and its right counterpart. A weight difference of 570 and 115 pounds seemed excessive to use so we wanted to see what was going on. The total fights difference of ~300 fights also intrigued us, but upon further testing, leaving those fights in the model actually helped accuracy and sensitivity, so we left those alone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="http://localhost:5419/#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Handling outliers</span></span>
<span id="cb6-2"><a href="http://localhost:5419/#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(data<span class="sc">$</span>l_weight_dif_lb <span class="sc">==</span> <span class="sc">-</span><span class="dv">570</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2204</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="http://localhost:5419/#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(data<span class="sc">$</span>l_weight_dif_lb <span class="sc">==</span> <span class="dv">115</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 887</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="http://localhost:5419/#cb10-1" aria-hidden="true" tabindex="-1"></a>weightOutliers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2204</span>,<span class="dv">887</span>)</span>
<span id="cb10-2"><a href="http://localhost:5419/#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="http://localhost:5419/#cb10-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="sc">!</span><span class="fu">row_number</span>() <span class="sc">%in%</span> weightOutliers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Removing these outliers increased model performance by ~7%</p>
</section>
<section id="relevant-columns-for-models" class="level2">
<h2 class="anchored" data-anchor-id="relevant-columns-for-models">Relevant Columns for Models<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#relevant-columns-for-models" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>As stated earlier, having left and right versions of the same predictor in a model would be unwise due to multicollinearity. Here, we specify what columns to use:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="http://localhost:5419/#cb11-1" aria-hidden="true" tabindex="-1"></a>l_stat <span class="ot">&lt;-</span> data[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">12</span>,<span class="dv">14</span>,<span class="dv">16</span><span class="sc">:</span><span class="dv">18</span>,<span class="dv">20</span>,<span class="dv">22</span><span class="sc">:</span><span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span><span class="sc">:</span><span class="dv">32</span>,<span class="dv">34</span>)]</span>
<span id="cb11-2"><a href="http://localhost:5419/#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="http://localhost:5419/#cb11-3" aria-hidden="true" tabindex="-1"></a>r_stat <span class="ot">&lt;-</span> data[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">13</span>,<span class="dv">15</span>,<span class="dv">17</span>,<span class="dv">19</span>,<span class="dv">21</span>,<span class="dv">27</span>,<span class="dv">29</span>,<span class="dv">33</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="center-and-scaling" class="level2">
<h2 class="anchored" data-anchor-id="center-and-scaling">Center and Scaling<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#center-and-scaling" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>The purpose of this step is to standardize all columns. For example, reach difference values are usually only going to be 0-10 while weight difference might be in the hundreds. This step ensures that all variables are treated equally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="http://localhost:5419/#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb12-2"><a href="http://localhost:5419/#cb12-2" aria-hidden="true" tabindex="-1"></a>divideData<span class="ot">&lt;-</span><span class="fu">createDataPartition</span>(l_stat<span class="sc">$</span>l_win, <span class="at">p=</span>.<span class="dv">8</span>, <span class="at">list=</span><span class="cn">FALSE</span>)</span>
<span id="cb12-3"><a href="http://localhost:5419/#cb12-3" aria-hidden="true" tabindex="-1"></a>train<span class="ot">&lt;-</span>l_stat[divideData,]</span>
<span id="cb12-4"><a href="http://localhost:5419/#cb12-4" aria-hidden="true" tabindex="-1"></a>test<span class="ot">&lt;-</span>l_stat[<span class="sc">-</span>divideData,]</span>
<span id="cb12-5"><a href="http://localhost:5419/#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="http://localhost:5419/#cb12-6" aria-hidden="true" tabindex="-1"></a>l_stat<span class="sc">$</span>l_win <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(l_stat<span class="sc">$</span>l_win)   <span class="co"># Making sure our dependent variable is a factor</span></span>
<span id="cb12-7"><a href="http://localhost:5419/#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="http://localhost:5419/#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Centering and scaling</span></span>
<span id="cb12-9"><a href="http://localhost:5419/#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Our dependent variable (l_win) needs to not be centered and scaled, so we took it out before preprocessing and added it back in at the end</span></span>
<span id="cb12-10"><a href="http://localhost:5419/#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="http://localhost:5419/#cb12-11" aria-hidden="true" tabindex="-1"></a>preprocessing <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(train <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>l_win), <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb12-12"><a href="http://localhost:5419/#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="http://localhost:5419/#cb12-13" aria-hidden="true" tabindex="-1"></a>traintransformed <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb12-14"><a href="http://localhost:5419/#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>l_win) <span class="sc">%&gt;%</span></span>
<span id="cb12-15"><a href="http://localhost:5419/#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(preprocessing, .) <span class="sc">%&gt;%</span></span>
<span id="cb12-16"><a href="http://localhost:5419/#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">l_win =</span> train<span class="sc">$</span>l_win)</span>
<span id="cb12-17"><a href="http://localhost:5419/#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="http://localhost:5419/#cb12-18" aria-hidden="true" tabindex="-1"></a>testtransformed <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb12-19"><a href="http://localhost:5419/#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>l_win) <span class="sc">%&gt;%</span></span>
<span id="cb12-20"><a href="http://localhost:5419/#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(preprocessing, .) <span class="sc">%&gt;%</span></span>
<span id="cb12-21"><a href="http://localhost:5419/#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">l_win =</span> test<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Always split before preprocessing. Splitting after processing gives the train set a peak on the test set.</p>
</section>
<section id="graphing-predictors-for-linearity" class="level2">
<h2 class="anchored" data-anchor-id="graphing-predictors-for-linearity">Graphing Predictors for Linearity<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#graphing-predictors-for-linearity" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>All predictors were graphed with their respective binary win variable as the dependent variable. Depending on the shape of the line, transformations were tested in modelling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="http://localhost:5419/#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(l_stat, <span class="fu">aes</span>(l_w.l_ratio, <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(l_win)))) <span class="sc">+</span>         <span class="co"># l_win needs to be in this format for ggplot</span></span>
<span id="cb13-2"><a href="http://localhost:5419/#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span>.<span class="dv">1</span>) <span class="sc">+</span> <span class="co"># alpha makes points more transparent</span></span>
<span id="cb13-3"><a href="http://localhost:5419/#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family=</span><span class="st">"binomial"</span>)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="http://localhost:5419/#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"l_w.l_ratio"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="http://localhost:5419/#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Predicted probability of l_win"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="./ufcproj_files/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We won’t include all 20 graphs here, just wanted to show this step and how we found that l_w.l_ratio benefited from being squared in the model. We produced these graphs and histograms (for logs) for all variables and tested transformations based on all the graphs, and this variable was the only one that benefited from a transformation.</p>
</section>
</section>
<section id="model-development" class="level1">
<h1>Model Development</h1>
<section id="comparing-logistic-and-lda-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-logistic-and-lda-models">Comparing Logistic and LDA models<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#comparing-logistic-and-lda-models" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<section id="logistic" class="level3">
<h3 class="anchored" data-anchor-id="logistic">Logistic:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#logistic" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="http://localhost:5419/#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding significant columns</span></span>
<span id="cb15-2"><a href="http://localhost:5419/#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(l_win<span class="sc">~</span>., <span class="at">family=</span>binomial, <span class="at">data=</span>traintransformed))    <span class="co"># Found our insignificant columns (remember w.l_ratio will be transformed)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = l_win ~ ., family = binomial, data = traintransformed)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         0.004021   0.029715   0.135   0.8924    
l_seniority        -0.206755   0.031660  -6.531 6.55e-11 ***
l_w.l_ratio        -0.144025   0.064918  -2.219   0.0265 *  
l_height_dif_cm    -0.038345   0.038337  -1.000   0.3172    
l_weight_dif_lb     0.030326   0.033944   0.893   0.3716    
l_reach_dif_cm      0.153921   0.038257   4.023 5.74e-05 ***
l_total_fights_dif  0.371920   0.033992  10.941  &lt; 2e-16 ***
l_win_difference    1.095341   0.073447  14.913  &lt; 2e-16 ***
l_WinStreak_dif     0.132128   0.030290   4.362 1.29e-05 ***
l_TKOReceived_dif   0.010947   0.029862   0.367   0.7139    
l_rustRing_dif      0.004757   0.029158   0.163   0.8704    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 7715.6  on 5565  degrees of freedom
Residual deviance: 6878.8  on 5555  degrees of freedom
  (182 observations deleted due to missingness)
AIC: 6900.8

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="http://localhost:5419/#cb17-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(<span class="fu">glm</span>(l_win<span class="sc">~</span>., <span class="at">family=</span>binomial, <span class="at">data=</span>traintransformed))   <span class="co"># Check to avoid multicollinearity</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       l_seniority        l_w.l_ratio    l_height_dif_cm    l_weight_dif_lb 
          1.153472           1.941730           1.705496           1.039071 
    l_reach_dif_cm l_total_fights_dif   l_win_difference    l_WinStreak_dif 
          1.674519           1.087155           2.003965           1.015712 
 l_TKOReceived_dif     l_rustRing_dif 
          1.109490           1.039673 </code></pre>
</div>
</div>
<p>Removing irrelevant variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="http://localhost:5419/#cb19-1" aria-hidden="true" tabindex="-1"></a>logisticreg <span class="ot">&lt;-</span> <span class="fu">glm</span>(l_win<span class="sc">~</span>l_seniority <span class="sc">+</span> <span class="fu">I</span>(l_w.l_ratio<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> l_reach_dif_cm <span class="sc">+</span> l_total_fights_dif <span class="sc">+</span> l_win_difference <span class="sc">+</span> l_WinStreak_dif, <span class="at">family=</span>binomial, <span class="at">data=</span>traintransformed)</span>
<span id="cb19-2"><a href="http://localhost:5419/#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="http://localhost:5419/#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logisticreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = l_win ~ l_seniority + I(l_w.l_ratio^2) + l_reach_dif_cm + 
    l_total_fights_dif + l_win_difference + l_WinStreak_dif, 
    family = binomial, data = traintransformed)

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         0.04644    0.02933   1.583    0.113    
l_seniority        -0.19708    0.03068  -6.425 1.32e-10 ***
I(l_w.l_ratio^2)   -0.06305    0.01072  -5.882 4.06e-09 ***
l_reach_dif_cm      0.13475    0.02977   4.527 5.98e-06 ***
l_total_fights_dif  0.37784    0.03371  11.207  &lt; 2e-16 ***
l_win_difference    1.10881    0.05928  18.705  &lt; 2e-16 ***
l_WinStreak_dif     0.12970    0.03009   4.311 1.63e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 7718.3  on 5567  degrees of freedom
Residual deviance: 6864.7  on 5561  degrees of freedom
  (180 observations deleted due to missingness)
AIC: 6878.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Gauging accuracy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="http://localhost:5419/#cb21-1" aria-hidden="true" tabindex="-1"></a>testNoNA <span class="ot">&lt;-</span> testtransformed[<span class="fu">complete.cases</span>(testtransformed),]    <span class="co"># to drop the few columns that had missing data</span></span>
<span id="cb21-2"><a href="http://localhost:5419/#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="http://localhost:5419/#cb21-3" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">&lt;-</span><span class="fu">predict</span>(logisticreg, testNoNA, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb21-4"><a href="http://localhost:5419/#cb21-4" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(probs <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb21-5"><a href="http://localhost:5419/#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="http://localhost:5419/#cb21-6" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">table</span>(pred, testNoNA<span class="sc">$</span>l_win)</span>
<span id="cb21-7"><a href="http://localhost:5419/#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred, testNoNA<span class="sc">$</span>l_win)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
pred   0   1
   0 495 211
   1 224 475</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="http://localhost:5419/#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pred<span class="sc">==</span>testNoNA<span class="sc">$</span>l_win)   <span class="co"># First output - accuracy </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6903915</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="http://localhost:5419/#cb25-1" aria-hidden="true" tabindex="-1"></a>Sensitivity <span class="ot">&lt;-</span> (table[<span class="dv">4</span>]<span class="sc">/</span>(table[<span class="dv">4</span>]<span class="sc">+</span>table[<span class="dv">3</span>])); Sensitivity  <span class="co"># Second output - accuracy predicing wins</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6924198</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="http://localhost:5419/#cb27-1" aria-hidden="true" tabindex="-1"></a>Specificity <span class="ot">&lt;-</span> (table[<span class="dv">1</span>]<span class="sc">/</span>(table[<span class="dv">1</span>]<span class="sc">+</span>table[<span class="dv">2</span>])); Specificity  <span class="co"># Third output - accuracy predicting losses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6884562</code></pre>
</div>
</div>
<p>Conclusion: Logistic model with a 50% confidence interval on processed data shows a sensitivity of 69%.</p>
</section>
<section id="lda" class="level3">
<h3 class="anchored" data-anchor-id="lda">LDA:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#lda" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="http://localhost:5419/#cb29-1" aria-hidden="true" tabindex="-1"></a>LDA<span class="ot">&lt;-</span> <span class="fu">lda</span>(l_win<span class="sc">~</span>l_seniority <span class="sc">+</span> <span class="fu">I</span>(l_w.l_ratio<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> l_reach_dif_cm <span class="sc">+</span> l_total_fights_dif <span class="sc">+</span> l_win_difference <span class="sc">+</span> l_WinStreak_dif, <span class="at">data=</span>traintransformed)</span>
<span id="cb29-2"><a href="http://localhost:5419/#cb29-2" aria-hidden="true" tabindex="-1"></a>LDA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
lda(l_win ~ l_seniority + I(l_w.l_ratio^2) + l_reach_dif_cm + 
    l_total_fights_dif + l_win_difference + l_WinStreak_dif, 
    data = traintransformed)

Prior probabilities of groups:
        0         1 
0.4949713 0.5050287 

Group means:
  l_seniority I(l_w.l_ratio^2) l_reach_dif_cm l_total_fights_dif
0   0.1493389        0.3940225    -0.08602174        -0.08652521
1  -0.1463649        1.6152463     0.09703572         0.09913826
  l_win_difference l_WinStreak_dif
0       -0.2928485     -0.10305884
1        0.2894550      0.09579721

Coefficients of linear discriminants:
                           LD1
l_seniority        -0.29453484
I(l_w.l_ratio^2)   -0.05243485
l_reach_dif_cm      0.16607358
l_total_fights_dif  0.45157614
l_win_difference    0.98745653
l_WinStreak_dif     0.18130055</code></pre>
</div>
</div>
<p>Gauging accuracy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="http://localhost:5419/#cb31-1" aria-hidden="true" tabindex="-1"></a>predLDA<span class="ot">&lt;-</span>LDA <span class="sc">%&gt;%</span> <span class="fu">predict</span>(testNoNA)</span>
<span id="cb31-2"><a href="http://localhost:5419/#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(predLDA<span class="sc">$</span>class<span class="sc">==</span>testNoNA<span class="sc">$</span>l_win)   <span class="co"># First output, accuracy</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6797153</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="http://localhost:5419/#cb33-1" aria-hidden="true" tabindex="-1"></a>LDAtable <span class="ot">&lt;-</span> <span class="fu">table</span>(predLDA<span class="sc">$</span>class,testNoNA<span class="sc">$</span>l_win)</span>
<span id="cb33-2"><a href="http://localhost:5419/#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="http://localhost:5419/#cb33-3" aria-hidden="true" tabindex="-1"></a>LDASensitivity <span class="ot">&lt;-</span> (LDAtable[<span class="dv">4</span>]<span class="sc">/</span>(LDAtable[<span class="dv">4</span>]<span class="sc">+</span>LDAtable[<span class="dv">3</span>])); LDASensitivity   <span class="co"># Second output - accuracy predicting wins</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7026239</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="http://localhost:5419/#cb35-1" aria-hidden="true" tabindex="-1"></a>LDASpecificity <span class="ot">&lt;-</span> (LDAtable[<span class="dv">1</span>]<span class="sc">/</span>(LDAtable[<span class="dv">1</span>]<span class="sc">+</span>LDAtable[<span class="dv">2</span>])); LDASpecificity   <span class="co"># Third output - accuracy predicting losses</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6578581</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="http://localhost:5419/#cb37-1" aria-hidden="true" tabindex="-1"></a>LDAtable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      0   1
  0 473 204
  1 246 482</code></pre>
</div>
</div>
<p>Conclusion: LDA model has a sensitivity of 70%, showing that it is very slightly better than a logistic model at classifying winners.</p>
</section>
<section id="bootstrapping" class="level3">
<h3 class="anchored" data-anchor-id="bootstrapping">Bootstrapping<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#bootstrapping" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>While testing models, we noticed that with different seeds, accuracy metrics went up or down by ~5%. This led us to believe that there was some variability in the data, showing the need to cross validate our models. Bootstrapping was a natural choice of method for this due to the size of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="http://localhost:5419/#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrapping required a train set with no NA values:</span></span>
<span id="cb39-2"><a href="http://localhost:5419/#cb39-2" aria-hidden="true" tabindex="-1"></a>trainNoNA <span class="ot">&lt;-</span> traintransformed[<span class="fu">complete.cases</span>(traintransformed),]</span>
<span id="cb39-3"><a href="http://localhost:5419/#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(trainNoNA<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="http://localhost:5419/#cb41-1" aria-hidden="true" tabindex="-1"></a>trainNoNA<span class="sc">$</span>l_win <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(trainNoNA<span class="sc">$</span>l_win)</span>
<span id="cb41-2"><a href="http://localhost:5419/#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="http://localhost:5419/#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrapped LDA Model</span></span>
<span id="cb41-4"><a href="http://localhost:5419/#cb41-4" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"boot"</span>, <span class="at">number =</span> <span class="dv">100</span>)</span>
<span id="cb41-5"><a href="http://localhost:5419/#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="http://localhost:5419/#cb41-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">train</span>(l_win<span class="sc">~</span>l_seniority <span class="sc">+</span> <span class="fu">I</span>(l_w.l_ratio<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> l_reach_dif_cm <span class="sc">+</span> l_total_fights_dif <span class="sc">+</span> l_win_difference <span class="sc">+</span> l_WinStreak_dif, <span class="at">data=</span>trainNoNA, <span class="at">method =</span> <span class="st">"lda"</span>,</span>
<span id="cb41-7"><a href="http://localhost:5419/#cb41-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> control)</span>
<span id="cb41-8"><a href="http://localhost:5419/#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="http://localhost:5419/#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Discriminant Analysis 

5566 samples
   6 predictor
   2 classes: '0', '1' 

No pre-processing
Resampling: Bootstrapped (100 reps) 
Summary of sample sizes: 5566, 5566, 5566, 5566, 5566, 5566, ... 
Resampling results:

  Accuracy   Kappa    
  0.6501703  0.3001067</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="http://localhost:5419/#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrapped Logistic Model</span></span>
<span id="cb43-2"><a href="http://localhost:5419/#cb43-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">train</span>(l_win<span class="sc">~</span>l_seniority <span class="sc">+</span> <span class="fu">I</span>(l_w.l_ratio<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> l_reach_dif_cm <span class="sc">+</span> l_total_fights_dif <span class="sc">+</span> l_win_difference <span class="sc">+</span> l_WinStreak_dif, <span class="at">data=</span>trainNoNA, <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb43-3"><a href="http://localhost:5419/#cb43-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">trControl =</span> control)</span>
<span id="cb43-4"><a href="http://localhost:5419/#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="http://localhost:5419/#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

5566 samples
   6 predictor
   2 classes: '0', '1' 

No pre-processing
Resampling: Bootstrapped (100 reps) 
Summary of sample sizes: 5566, 5566, 5566, 5566, 5566, 5566, ... 
Resampling results:

  Accuracy  Kappa    
  0.654198  0.3083167</code></pre>
</div>
</div>
<p>We can see here that both models have a similar accuracy when bootstrapped, and logistic is actually the tiniest amount more accurate. Since logistic regression is simpler to understand than LDA, we chose to go with that bootstrapped model.</p>
</section>
</section>
</section>
<section id="predicting-the-upcoming-fights-from-dec.-7th-with-chosen-model" class="level1">
<h1>Predicting the Upcoming Fights from Dec.&nbsp;7th with Chosen Model:</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="http://localhost:5419/#cb45-1" aria-hidden="true" tabindex="-1"></a>newFights <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/lwhite01/Data/main/Dec7Fights.csv'</span>)</span>
<span id="cb45-2"><a href="http://localhost:5419/#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newFights) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          l_FullName        r_FullName l_fighter_height_cm r_fighter_height_cm
1        Kai Asakura Alexandre Pantoja              172.00              165.10
2 RECORD Kai Asakura Alexandre Pantoja              172.00              165.10
3 Shavakat Rakhmonov         Ian Garry              185.42              187.96
4        Citryl Gane  Alexander Volkov              195.58              201.00
5     Bryce Mitchell       Kron Gracie              177.80              175.26
6      Nate Landwehr        Dooho Choi              175.26              177.80
  l_fighter_weight_lbs r_fighter_weight_lbs l_fighter_reach_cm
1                125.0                125.0             175.00
2                125.0                125.0             175.00
3                171.0                170.0             195.58
4                250.0                258.0             205.74
5                145.5                145.0             101.60
6                159.0                158.7             182.88
  r_fighter_reach_cm l_fighter_age r_fighter_age l_fighter_w l_fighter_l
1             173.00            31            35           0           0
2             173.00            31            35          21           4
3             189.23            30            27          18           0
4             203.20            35            36          12           2
5              99.06            30            36          16           3
6             177.80            37            34          18           5
  r_fighter_w r_fighter_l l_WinStreak r_WinStreak l_TKOReceived r_TKOReceived
1          28           5           2           6             3             0
2          28           5           2           6             3             0
3          15           0          18          15             0             0
4          38          10           1           4             0             2
5           5           2           0           0             1             0
6          15           4           1           1             2             2
  l_rust_ring r_rust_ring l_seniority r_seniority l_height_dif_cm
1          11           7          -4           4            6.90
2          11           7          -4           4            6.90
3          11           5           3          -3           -2.54
4          15           5          -1           1           -5.42
5          11          19          -6           6            2.54
6           8           4           3          -3           -2.54
  r_height_dif_cm l_weight_dif_lb r_weight_dif_lb l_reach_dif_cm r_reach_dif_cm
1           -6.90             0.0             0.0           2.00          -2.00
2           -6.90             0.0             0.0           2.00          -2.00
3            2.54             1.0            -1.0           6.35          -6.35
4            5.42            -8.0             8.0           2.54          -2.54
5           -2.54             0.5            -0.5           2.54          -2.54
6            2.54             0.3            -0.3           5.08          -5.08
  l_total_fights_dif r_total_fights_dif l_w.l_ratio r_w.l_ratio l_total_fights
1                -33                 33    0.000000        5.60              0
2                 -8                  8    5.250000        5.60             25
3                  3                 -3   18.000000       15.00             18
4                -34                 34    6.000000        3.80             14
5                 12                -12    5.333333        2.50             19
6                  4                 -4    3.600000        3.75             23
  r_total_fights l_win_difference r_win_difference l_WinStreak_dif
1             33        -5.600000         5.600000              -4
2             33        -0.350000         0.350000              -4
3             15         3.000000        -3.000000               3
4             48         2.200000        -2.200000              -3
5              7         2.833333        -2.833333               0
6             19        -0.150000         0.150000               0
  r_WinStreak_dif l_TKOReceived_dif r_TKOReceived_dif l_rustRing_dif
1               4                 3                -3              4
2               4                 3                -3              4
3              -3                 0                 0              6
4               3                -2                 2             10
5               0                 1                -1             -8
6               0                 0                 0              4
  r_rustRing_dif
1             -4
2             -4
3             -6
4            -10
5              8
6             -4</code></pre>
</div>
</div>
<p>Kai Asakura vs Alexandre Pantoja appears twice since Asakura is from a different league in Japan and this is his first UFC fight. Therefore, his total fights would’ve equaled 0 in our dataset since we based all of our metrics off UFC fights. The first row has him with 0 total fights, and the second row has him with his fights from the Japanese league. We tested both to make sure this wouldn’t be an issue.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="http://localhost:5419/#cb47-1" aria-hidden="true" tabindex="-1"></a>newSelect <span class="ot">&lt;-</span> newFights[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">20</span>,<span class="dv">22</span><span class="sc">:</span><span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span><span class="sc">:</span><span class="dv">34</span>,<span class="dv">36</span>,<span class="dv">38</span>,<span class="dv">39</span><span class="sc">:</span><span class="dv">42</span>)]   <span class="co"># Only columns pertaining to left fighters</span></span>
<span id="cb47-2"><a href="http://localhost:5419/#cb47-2" aria-hidden="true" tabindex="-1"></a>noName <span class="ot">&lt;-</span> newSelect[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)]   <span class="co"># Removing names from the dataset to use for analysis</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="prediction-results" class="level2">
<h2 class="anchored" data-anchor-id="prediction-results">Prediction Results<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#prediction-results" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>The column on the right hand side of the table below shows who is predicted to win each upcoming fight based on our bootstrapped logistic model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="http://localhost:5419/#cb48-1" aria-hidden="true" tabindex="-1"></a>newPred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model2, noName)</span>
<span id="cb48-2"><a href="http://localhost:5419/#cb48-2" aria-hidden="true" tabindex="-1"></a>newSelect<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> newPred</span>
<span id="cb48-3"><a href="http://localhost:5419/#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="http://localhost:5419/#cb48-4" aria-hidden="true" tabindex="-1"></a>newSelect<span class="sc">$</span>predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb48-5"><a href="http://localhost:5419/#cb48-5" aria-hidden="true" tabindex="-1"></a>  newSelect<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb48-6"><a href="http://localhost:5419/#cb48-6" aria-hidden="true" tabindex="-1"></a>  newSelect<span class="sc">$</span>l_FullName, </span>
<span id="cb48-7"><a href="http://localhost:5419/#cb48-7" aria-hidden="true" tabindex="-1"></a>  newSelect<span class="sc">$</span>r_FullName</span>
<span id="cb48-8"><a href="http://localhost:5419/#cb48-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-9"><a href="http://localhost:5419/#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="http://localhost:5419/#cb48-10" aria-hidden="true" tabindex="-1"></a>newSelect</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           l_FullName        r_FullName l_seniority l_reach_dif_cm
1         Kai Asakura Alexandre Pantoja          -4           2.00
2  RECORD Kai Asakura Alexandre Pantoja          -4           2.00
3  Shavakat Rakhmonov         Ian Garry           3           6.35
4         Citryl Gane  Alexander Volkov          -1           2.54
5      Bryce Mitchell       Kron Gracie          -6           2.54
6       Nate Landwehr        Dooho Choi           3           5.08
7      Dominick Reyes     Anthony Smith          -1           2.54
8       Vicente Luque    Themba Gorimbo          -1          -3.81
9       Movsar Evloev Aljamain Sterling          -5           3.81
10        Randy Brown      Bryan Battle           4           2.54
11      Chris Weidman       Eryk Anders           3           7.62
12        Cody Durden        Joshya Van          11           5.08
13     Michael Chiesa       Max Griffin          -2          -1.27
14         Clay Guida      Chase Hooper          18         -10.16
15  Kennedy Nzechukwu      Lukaz Brzeki           0          12.70
16          Jake Paul        Mike Tyson         -31          12.70
   l_total_fights_dif l_w.l_ratio l_win_difference l_WinStreak_dif
1                 -33    0.000000      -5.60000000              -4
2                  -8    5.250000      -0.35000000              -4
3                   3   18.000000       3.00000000               3
4                 -34    6.000000       2.20000000              -3
5                  12    5.333333       2.83333333               0
6                   4    3.600000      -0.15000000               0
7                 -41    3.250000       1.35000000               1
8                  14    2.200000      -1.30000000              -4
9                 -10   18.000000      12.00000000              17
10                 10    3.800000      -2.20000000               2
11                 -3    2.285714       0.03571429               0
12                 10    2.833333      -2.66666667               0
13                 -4    2.714286       0.71428571               0
14                 43    1.809524      -2.52380952              -3
15                  4    2.600000       0.80000000               1
16                -44   11.000000       2.66666667               4
   predicted_l_win  predicted_winner
1                0 Alexandre Pantoja
2                0 Alexandre Pantoja
3                0         Ian Garry
4                0  Alexander Volkov
5                1    Bryce Mitchell
6                1     Nate Landwehr
7                0     Anthony Smith
8                1     Vicente Luque
9                0 Aljamain Sterling
10               1       Randy Brown
11               0       Eryk Anders
12               0        Joshya Van
13               0       Max Griffin
14               1        Clay Guida
15               1 Kennedy Nzechukwu
16               0        Mike Tyson</code></pre>
</div>
</div>
<p>Compared to odds setter favorites: (as of 12/6/24 7pm on FanDuel) <br> Odds meanings: <br> +300 means a $10 bet wins $30 (favored to lose) <br> -400 means a $10 bet wins $2.50 (favored to win) <br></p>
<p>Dooho Choi vs Nate Landwehr: <br> Dooho Choi +114 <br> Nate Landwehr -140 <br> Our model predicts Nate Landwehr <br></p>
<p>Bryce Mitchell vs Kron Gracie: <br> Bryce Mitchell -750 <br> Kron Gracie +490 <br> Our model predicts Bryce Mitchell <br></p>
<p>Ciryl Gane vs Alexander Volkov: <br> Ciryl Gane -400 <br> Alexander Volkov +290 <br> Our model predicts Alexander Volkov <br></p>
<p>Shavkat Rakhmonov vs Ian Garry: <br> Shavkat Rakhmonov -400 <br> Ian Garry +300 <br> Our model predicts Ian Garry <br></p>
<p>Alexandre Pantoja vs Kai Asakura: <br> Alexandre Pantoja -260 <br> Kai Asakura +205 <br> Our model predicts Alexandre Pantoja <br></p>
</section>
</section>
<section id="what-happened-in-real-life" class="level1">
<h1>What Happened in Real Life?</h1>
<p>Our model performed very poorly in real life (42% accurate), leading us to go back to the drawing board. One issue we found was that we used models trained on pre-processed data to predict on non-pre-processed data. When we fixed that issue, the it still did not really increase performance. We also went back through all the fights in November to see if December 7th was just a really unlucky day for our model. Here’s what we found:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="http://localhost:5419/#cb50-1" aria-hidden="true" tabindex="-1"></a>pastFights <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/lwhite01/Data/main/pastFights.csv'</span>)</span>
<span id="cb50-2"><a href="http://localhost:5419/#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="http://localhost:5419/#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># DECEMBER 7th:</span></span>
<span id="cb50-4"><a href="http://localhost:5419/#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="http://localhost:5419/#cb50-5" aria-hidden="true" tabindex="-1"></a>selDec7 <span class="ot">&lt;-</span> pastFights[<span class="fu">c</span>(<span class="dv">26</span><span class="sc">:</span><span class="dv">39</span>),<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">37</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb50-6"><a href="http://localhost:5419/#cb50-6" aria-hidden="true" tabindex="-1"></a>nnwDec7 <span class="ot">&lt;-</span> selDec7[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">10</span>)]</span>
<span id="cb50-7"><a href="http://localhost:5419/#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="http://localhost:5419/#cb50-8" aria-hidden="true" tabindex="-1"></a>pfPredDec7 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, nnwDec7)</span>
<span id="cb50-9"><a href="http://localhost:5419/#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="http://localhost:5419/#cb50-10" aria-hidden="true" tabindex="-1"></a>selDec7<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> pfPredDec7</span>
<span id="cb50-11"><a href="http://localhost:5419/#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="http://localhost:5419/#cb50-12" aria-hidden="true" tabindex="-1"></a>selDec7<span class="sc">$</span>predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb50-13"><a href="http://localhost:5419/#cb50-13" aria-hidden="true" tabindex="-1"></a>  selDec7<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb50-14"><a href="http://localhost:5419/#cb50-14" aria-hidden="true" tabindex="-1"></a>  selDec7<span class="sc">$</span>l_FullName, </span>
<span id="cb50-15"><a href="http://localhost:5419/#cb50-15" aria-hidden="true" tabindex="-1"></a>  selDec7<span class="sc">$</span>r_FullName</span>
<span id="cb50-16"><a href="http://localhost:5419/#cb50-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-17"><a href="http://localhost:5419/#cb50-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-18"><a href="http://localhost:5419/#cb50-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(selDec7<span class="sc">$</span>predicted_l_win<span class="sc">==</span>selDec7<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4285714</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="http://localhost:5419/#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NOVEMBER 23rd:</span></span>
<span id="cb52-2"><a href="http://localhost:5419/#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="http://localhost:5419/#cb52-3" aria-hidden="true" tabindex="-1"></a>selNov23 <span class="ot">&lt;-</span> pastFights[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>),<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">37</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb52-4"><a href="http://localhost:5419/#cb52-4" aria-hidden="true" tabindex="-1"></a>nnwNov23 <span class="ot">&lt;-</span> selNov23[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">10</span>)]</span>
<span id="cb52-5"><a href="http://localhost:5419/#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="http://localhost:5419/#cb52-6" aria-hidden="true" tabindex="-1"></a>pfPredNov23 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, nnwNov23)</span>
<span id="cb52-7"><a href="http://localhost:5419/#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="http://localhost:5419/#cb52-8" aria-hidden="true" tabindex="-1"></a>selNov23<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> pfPredNov23</span>
<span id="cb52-9"><a href="http://localhost:5419/#cb52-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-10"><a href="http://localhost:5419/#cb52-10" aria-hidden="true" tabindex="-1"></a>selNov23<span class="sc">$</span>predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb52-11"><a href="http://localhost:5419/#cb52-11" aria-hidden="true" tabindex="-1"></a>  selNov23<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb52-12"><a href="http://localhost:5419/#cb52-12" aria-hidden="true" tabindex="-1"></a>  selNov23<span class="sc">$</span>l_FullName, </span>
<span id="cb52-13"><a href="http://localhost:5419/#cb52-13" aria-hidden="true" tabindex="-1"></a>  selNov23<span class="sc">$</span>r_FullName</span>
<span id="cb52-14"><a href="http://localhost:5419/#cb52-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-15"><a href="http://localhost:5419/#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="http://localhost:5419/#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(selNov23<span class="sc">$</span>predicted_l_win<span class="sc">==</span>selNov23<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5384615</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="http://localhost:5419/#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NOVEMBER 16th:</span></span>
<span id="cb54-2"><a href="http://localhost:5419/#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="http://localhost:5419/#cb54-3" aria-hidden="true" tabindex="-1"></a>selNov16 <span class="ot">&lt;-</span> pastFights[<span class="fu">c</span>(<span class="dv">14</span><span class="sc">:</span><span class="dv">25</span>),<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">37</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb54-4"><a href="http://localhost:5419/#cb54-4" aria-hidden="true" tabindex="-1"></a>nnwNov16 <span class="ot">&lt;-</span> selNov16[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">10</span>)]</span>
<span id="cb54-5"><a href="http://localhost:5419/#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="http://localhost:5419/#cb54-6" aria-hidden="true" tabindex="-1"></a>pfPredNov16 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, nnwNov16)</span>
<span id="cb54-7"><a href="http://localhost:5419/#cb54-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-8"><a href="http://localhost:5419/#cb54-8" aria-hidden="true" tabindex="-1"></a>selNov16<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> pfPredNov16</span>
<span id="cb54-9"><a href="http://localhost:5419/#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="http://localhost:5419/#cb54-10" aria-hidden="true" tabindex="-1"></a>selNov16<span class="sc">$</span>predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb54-11"><a href="http://localhost:5419/#cb54-11" aria-hidden="true" tabindex="-1"></a>  selNov16<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb54-12"><a href="http://localhost:5419/#cb54-12" aria-hidden="true" tabindex="-1"></a>  selNov16<span class="sc">$</span>l_FullName, </span>
<span id="cb54-13"><a href="http://localhost:5419/#cb54-13" aria-hidden="true" tabindex="-1"></a>  selNov16<span class="sc">$</span>r_FullName</span>
<span id="cb54-14"><a href="http://localhost:5419/#cb54-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-15"><a href="http://localhost:5419/#cb54-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-16"><a href="http://localhost:5419/#cb54-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(selNov16<span class="sc">$</span>predicted_l_win<span class="sc">==</span>selNov16<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5833333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="http://localhost:5419/#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># NOVEMBER 9th:</span></span>
<span id="cb56-2"><a href="http://localhost:5419/#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="http://localhost:5419/#cb56-3" aria-hidden="true" tabindex="-1"></a>selNov9 <span class="ot">&lt;-</span> pastFights[<span class="fu">c</span>(<span class="dv">40</span><span class="sc">:</span><span class="dv">50</span>),<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">37</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb56-4"><a href="http://localhost:5419/#cb56-4" aria-hidden="true" tabindex="-1"></a>nnwNov9 <span class="ot">&lt;-</span> selNov9[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">10</span>)]</span>
<span id="cb56-5"><a href="http://localhost:5419/#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="http://localhost:5419/#cb56-6" aria-hidden="true" tabindex="-1"></a>pfPredNov9 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, nnwNov9)</span>
<span id="cb56-7"><a href="http://localhost:5419/#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="http://localhost:5419/#cb56-8" aria-hidden="true" tabindex="-1"></a>selNov9<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> pfPredNov9</span>
<span id="cb56-9"><a href="http://localhost:5419/#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="http://localhost:5419/#cb56-10" aria-hidden="true" tabindex="-1"></a>selNov9<span class="sc">$</span>predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb56-11"><a href="http://localhost:5419/#cb56-11" aria-hidden="true" tabindex="-1"></a>  selNov9<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb56-12"><a href="http://localhost:5419/#cb56-12" aria-hidden="true" tabindex="-1"></a>  selNov9<span class="sc">$</span>l_FullName, </span>
<span id="cb56-13"><a href="http://localhost:5419/#cb56-13" aria-hidden="true" tabindex="-1"></a>  selNov9<span class="sc">$</span>r_FullName</span>
<span id="cb56-14"><a href="http://localhost:5419/#cb56-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-15"><a href="http://localhost:5419/#cb56-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-16"><a href="http://localhost:5419/#cb56-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(selNov9<span class="sc">$</span>predicted_l_win<span class="sc">==</span>selNov9<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4545455</code></pre>
</div>
</div>
<p>As you can see, it flip flops around 50%. When we tested the model on all of those fights together, we found an accuracy of 50%:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="http://localhost:5419/#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy including Dec 7th's event and past 3 weekends</span></span>
<span id="cb58-2"><a href="http://localhost:5419/#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 50 fights total</span></span>
<span id="cb58-3"><a href="http://localhost:5419/#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="http://localhost:5419/#cb58-4" aria-hidden="true" tabindex="-1"></a>sel <span class="ot">&lt;-</span> pastFights[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">37</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb58-5"><a href="http://localhost:5419/#cb58-5" aria-hidden="true" tabindex="-1"></a>nnw <span class="ot">&lt;-</span> sel[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">10</span>)]</span>
<span id="cb58-6"><a href="http://localhost:5419/#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="http://localhost:5419/#cb58-7" aria-hidden="true" tabindex="-1"></a>pfPred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, nnw)</span>
<span id="cb58-8"><a href="http://localhost:5419/#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="http://localhost:5419/#cb58-9" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> pfPred</span>
<span id="cb58-10"><a href="http://localhost:5419/#cb58-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-11"><a href="http://localhost:5419/#cb58-11" aria-hidden="true" tabindex="-1"></a>sel<span class="sc">$</span>predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb58-12"><a href="http://localhost:5419/#cb58-12" aria-hidden="true" tabindex="-1"></a>  sel<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb58-13"><a href="http://localhost:5419/#cb58-13" aria-hidden="true" tabindex="-1"></a>  sel<span class="sc">$</span>l_FullName, </span>
<span id="cb58-14"><a href="http://localhost:5419/#cb58-14" aria-hidden="true" tabindex="-1"></a>  sel<span class="sc">$</span>r_FullName</span>
<span id="cb58-15"><a href="http://localhost:5419/#cb58-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-16"><a href="http://localhost:5419/#cb58-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-17"><a href="http://localhost:5419/#cb58-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sel<span class="sc">$</span>predicted_l_win<span class="sc">==</span>sel<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5</code></pre>
</div>
</div>
<p>The bootstrapped (66% accuracy) and base LDA model (71% accuracy) were both ran on the new fights, predicting the same results. With an unlucky event Dec 7th (42% accuracy), and the model’s 50% accuracy when you include the past couple weekends, the data we trained on most likely does not reflect the UFC well. Since our data dates back to 1994, and there were plenty of ‘gimmick fights’ in the 90s (for example, David vs Goliath events), there are most likely more outliers inflating the accuracy metrics and some other veracity issues. Or it could be a case of when predicting for 10 fights, vs thousands, it’s much more variable what accuracy we will get. The more and more fights you add, it could go towards a 66% accuracy rate.</p>
<p>This made us redo our project and focus on a higher confidence interval (than just 50%) to classify a winner. This is making it so that the models will only choose a winner if it feels very sure they will win. This changes what l_win and r_win mean a little bit. A 1 still means a predicted win, but a 0 just means the models are not sure. Lets develop these models below:</p>
</section>
<section id="conservative-model" class="level1">
<h1>Conservative Model</h1>
<section id="preparing-the-data-again" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-data-again">Preparing the data again:<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#preparing-the-data-again" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="http://localhost:5419/#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DATA</span></span>
<span id="cb60-2"><a href="http://localhost:5419/#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="http://localhost:5419/#cb60-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/lwhite01/Data/main/finalFighter.csv'</span>)</span>
<span id="cb60-4"><a href="http://localhost:5419/#cb60-4" aria-hidden="true" tabindex="-1"></a>col <span class="ot">&lt;-</span> <span class="fu">as.list</span>(<span class="fu">colnames</span>(data))</span>
<span id="cb60-5"><a href="http://localhost:5419/#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="http://localhost:5419/#cb60-6" aria-hidden="true" tabindex="-1"></a>weightOutliers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2204</span>,<span class="dv">887</span>)</span>
<span id="cb60-7"><a href="http://localhost:5419/#cb60-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">row_number</span>() <span class="sc">%in%</span> weightOutliers)</span>
<span id="cb60-8"><a href="http://localhost:5419/#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="http://localhost:5419/#cb60-9" aria-hidden="true" tabindex="-1"></a>l_stat <span class="ot">&lt;-</span> data[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">12</span>,<span class="dv">14</span>,<span class="dv">16</span><span class="sc">:</span><span class="dv">18</span>,<span class="dv">20</span>,<span class="dv">22</span>,<span class="dv">23</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">31</span>,<span class="dv">32</span>,<span class="dv">34</span>)]</span>
<span id="cb60-10"><a href="http://localhost:5419/#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(l_stat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "l_win"              "l_seniority"        "l_w.l_ratio"       
 [4] "l_height_dif_cm"    "l_weight_dif_lb"    "l_reach_dif_cm"    
 [7] "l_total_fights_dif" "l_win_difference"   "l_WinStreak_dif"   
[10] "l_TKOReceived_dif"  "l_rustRing_dif"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="http://localhost:5419/#cb62-1" aria-hidden="true" tabindex="-1"></a>r_stat <span class="ot">&lt;-</span> data[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">13</span>,<span class="dv">15</span>,<span class="dv">17</span><span class="sc">:</span><span class="dv">19</span>,<span class="dv">21</span>,<span class="dv">23</span><span class="sc">:</span><span class="dv">27</span>,<span class="dv">29</span>,<span class="dv">31</span><span class="sc">:</span><span class="dv">33</span>)]</span>
<span id="cb62-2"><a href="http://localhost:5419/#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(r_stat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "r_win"              "r_seniority"        "r_w.l_ratio"       
 [4] "r_height_dif_cm"    "r_weight_dif_lb"    "r_reach_dif_cm"    
 [7] "r_total_fights_dif" "r_win_difference"   "r_WinStreak_dif"   
[10] "r_TKOReceived_dif"  "r_rustRing_dif"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="http://localhost:5419/#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TESTING</span><span class="co"> MODELS</span></span>
<span id="cb64-2"><a href="http://localhost:5419/#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="http://localhost:5419/#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb64-4"><a href="http://localhost:5419/#cb64-4" aria-hidden="true" tabindex="-1"></a>divideData<span class="ot">&lt;-</span><span class="fu">createDataPartition</span>(l_stat<span class="sc">$</span>l_win, <span class="at">p=</span>.<span class="dv">8</span>, <span class="at">list=</span><span class="cn">FALSE</span>)</span>
<span id="cb64-5"><a href="http://localhost:5419/#cb64-5" aria-hidden="true" tabindex="-1"></a>train<span class="ot">&lt;-</span>l_stat[divideData,]</span>
<span id="cb64-6"><a href="http://localhost:5419/#cb64-6" aria-hidden="true" tabindex="-1"></a>test<span class="ot">&lt;-</span>l_stat[<span class="sc">-</span>divideData,]</span>
<span id="cb64-7"><a href="http://localhost:5419/#cb64-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-8"><a href="http://localhost:5419/#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(l_stat<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="http://localhost:5419/#cb66-1" aria-hidden="true" tabindex="-1"></a>l_stat<span class="sc">$</span>l_win <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(l_stat<span class="sc">$</span>l_win)</span>
<span id="cb66-2"><a href="http://localhost:5419/#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="http://localhost:5419/#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Preprocess the data (exclude the target variable l_win)</span></span>
<span id="cb66-4"><a href="http://localhost:5419/#cb66-4" aria-hidden="true" tabindex="-1"></a>preprocessing <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(train <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>l_win), <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb66-5"><a href="http://localhost:5419/#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="http://localhost:5419/#cb66-6" aria-hidden="true" tabindex="-1"></a>traintransformed <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb66-7"><a href="http://localhost:5419/#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>l_win) <span class="sc">%&gt;%</span></span>
<span id="cb66-8"><a href="http://localhost:5419/#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(preprocessing, .) <span class="sc">%&gt;%</span></span>
<span id="cb66-9"><a href="http://localhost:5419/#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">l_win =</span> train<span class="sc">$</span>l_win)</span>
<span id="cb66-10"><a href="http://localhost:5419/#cb66-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-11"><a href="http://localhost:5419/#cb66-11" aria-hidden="true" tabindex="-1"></a>testtransformed <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb66-12"><a href="http://localhost:5419/#cb66-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>l_win) <span class="sc">%&gt;%</span></span>
<span id="cb66-13"><a href="http://localhost:5419/#cb66-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(preprocessing, .) <span class="sc">%&gt;%</span></span>
<span id="cb66-14"><a href="http://localhost:5419/#cb66-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">l_win =</span> test<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-development-focusing-on-precision" class="level2">
<h2 class="anchored" data-anchor-id="model-development-focusing-on-precision">Model development focusing on precision<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#model-development-focusing-on-precision" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="http://localhost:5419/#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># FOCUSING ON PRECISION (TP/TP+FP)</span></span>
<span id="cb67-2"><a href="http://localhost:5419/#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="http://localhost:5419/#cb67-3" aria-hidden="true" tabindex="-1"></a>logisticreg <span class="ot">&lt;-</span> <span class="fu">glm</span>(l_win<span class="sc">~</span>l_seniority <span class="sc">+</span> <span class="fu">I</span>(l_w.l_ratio<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> l_reach_dif_cm <span class="sc">+</span> l_total_fights_dif <span class="sc">+</span> l_win_difference <span class="sc">+</span> l_WinStreak_dif, <span class="at">family=</span>binomial, <span class="at">data=</span>traintransformed)</span>
<span id="cb67-4"><a href="http://localhost:5419/#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logisticreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = l_win ~ l_seniority + I(l_w.l_ratio^2) + l_reach_dif_cm + 
    l_total_fights_dif + l_win_difference + l_WinStreak_dif, 
    family = binomial, data = traintransformed)

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         0.04644    0.02933   1.583    0.113    
l_seniority        -0.19708    0.03068  -6.425 1.32e-10 ***
I(l_w.l_ratio^2)   -0.06305    0.01072  -5.882 4.06e-09 ***
l_reach_dif_cm      0.13475    0.02977   4.527 5.98e-06 ***
l_total_fights_dif  0.37784    0.03371  11.207  &lt; 2e-16 ***
l_win_difference    1.10881    0.05928  18.705  &lt; 2e-16 ***
l_WinStreak_dif     0.12970    0.03009   4.311 1.63e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 7718.3  on 5567  degrees of freedom
Residual deviance: 6864.7  on 5561  degrees of freedom
  (180 observations deleted due to missingness)
AIC: 6878.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="http://localhost:5419/#cb69-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(logisticreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       l_seniority   I(l_w.l_ratio^2)     l_reach_dif_cm l_total_fights_dif 
          1.078557           1.507273           1.010185           1.062997 
  l_win_difference    l_WinStreak_dif 
          1.576397           1.004747 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="http://localhost:5419/#cb71-1" aria-hidden="true" tabindex="-1"></a>testNoNA <span class="ot">&lt;-</span> testtransformed[<span class="fu">complete.cases</span>(testtransformed),]</span>
<span id="cb71-2"><a href="http://localhost:5419/#cb71-2" aria-hidden="true" tabindex="-1"></a>testnnNp <span class="ot">&lt;-</span> test[<span class="fu">complete.cases</span>(test),]</span>
<span id="cb71-3"><a href="http://localhost:5419/#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="http://localhost:5419/#cb71-4" aria-hidden="true" tabindex="-1"></a>probs<span class="ot">&lt;-</span><span class="fu">predict</span>(logisticreg, testNoNA, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb71-5"><a href="http://localhost:5419/#cb71-5" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(probs <span class="sc">&gt;</span> <span class="fl">0.7</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb71-6"><a href="http://localhost:5419/#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="http://localhost:5419/#cb71-7" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">table</span>(pred, testNoNA<span class="sc">$</span>l_win)</span>
<span id="cb71-8"><a href="http://localhost:5419/#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred, testNoNA<span class="sc">$</span>l_win)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
pred   0   1
   0 686 539
   1  33 147</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="http://localhost:5419/#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pred<span class="sc">==</span>testNoNA<span class="sc">$</span>l_win) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5928826</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="http://localhost:5419/#cb75-1" aria-hidden="true" tabindex="-1"></a>Precision <span class="ot">&lt;-</span> (table[<span class="dv">4</span>]<span class="sc">/</span>(table[<span class="dv">4</span>]<span class="sc">+</span>table[<span class="dv">2</span>])); Precision</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8166667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="http://localhost:5419/#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.9 threshold has 91% precision - 22 tp and 2 fp</span></span>
<span id="cb77-2"><a href="http://localhost:5419/#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.8 threshold has 83% precision - 56 tp and 11 fp</span></span>
<span id="cb77-3"><a href="http://localhost:5419/#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.7 threshold has 82% precision - 147 tp and 33 fp</span></span>
<span id="cb77-4"><a href="http://localhost:5419/#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.6 threshold has 76% precision - 310 tp and 98 fp</span></span>
<span id="cb77-5"><a href="http://localhost:5419/#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="http://localhost:5419/#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="co"># I like 0.7 the most</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The reason for focusing on precision instead of sensitivity is that the goal here is to accurately predict winners. The only negative consequence in this scenario are FPs, because you are going to bet on what the model predicts as a 1. FNs and TNs don’t really matter, we’re just trying to maximize TPs to FPs.</p>
<p>A 70% threshold was chosen because that had the highest precision rate while still outputting a lot of predictions. Increasing the threshold to 80% only improved precision by 1%, but cut our quantity of prediction outputs by 3.</p>
<p>A model was also ran for the right fighters, and showed the same precision metrics.</p>
</section>
<section id="testing-on-november-december-fights" class="level2">
<h2 class="anchored" data-anchor-id="testing-on-november-december-fights">Testing on November-December Fights<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:5419/#testing-on-november-december-fights" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>Preparing Data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="http://localhost:5419/#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PREDICTING OLD FIGHTS</span></span>
<span id="cb78-2"><a href="http://localhost:5419/#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="http://localhost:5419/#cb78-3" aria-hidden="true" tabindex="-1"></a>pastFights <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/lwhite01/Data/main/pastFights.csv'</span>)</span>
<span id="cb78-4"><a href="http://localhost:5419/#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(pastFights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "l_FullName"           "r_FullName"           "l_fighter_height_cm" 
 [4] "r_fighter_height_cm"  "l_fighter_weight_lbs" "r_fighter_weight_lbs"
 [7] "l_fighter_reach_cm"   "r_fighter_reach_cm"   "l_fighter_age"       
[10] "r_fighter_age"        "l_fighter_w"          "l_fighter_l"         
[13] "r_fighter_w"          "r_fighter_l"          "l_WinStreak"         
[16] "r_WinStreak"          "l_seniority"          "r_seniority"         
[19] "l_height_dif_cm"      "r_height_dif_cm"      "l_weight_dif_lb"     
[22] "r_weight_dif_lb"      "l_reach_dif_cm"       "r_reach_dif_cm"      
[25] "l_total_fights"       "r_total_fights"       "l_w.l_ratio"         
[28] "r_w.l_ratio"          "l_total_fights_dif"   "r_total_fights_dif"  
[31] "l_win_difference"     "r_win_difference"     "l_WinStreak_dif"     
[34] "r_WinStreak_dif"      "l_win"                "r_win"               
[37] "X"                    "X.1"                 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="http://localhost:5419/#cb80-1" aria-hidden="true" tabindex="-1"></a>leftSel <span class="ot">&lt;-</span> pastFights[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>,<span class="dv">24</span>,<span class="dv">25</span>,<span class="dv">26</span>,<span class="dv">28</span>,<span class="dv">30</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">36</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb80-2"><a href="http://localhost:5419/#cb80-2" aria-hidden="true" tabindex="-1"></a>rightSel <span class="ot">&lt;-</span> pastFights[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">16</span>,<span class="dv">17</span>,<span class="dv">19</span><span class="sc">:</span><span class="dv">23</span>,<span class="dv">25</span><span class="sc">:</span><span class="dv">27</span>,<span class="dv">29</span>,<span class="dv">31</span>,<span class="dv">33</span>,<span class="dv">35</span>,<span class="dv">37</span><span class="sc">:</span><span class="dv">38</span>)]</span>
<span id="cb80-3"><a href="http://localhost:5419/#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(leftSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "l_FullName"         "r_FullName"         "l_seniority"       
[4] "l_reach_dif_cm"     "l_w.l_ratio"        "l_total_fights_dif"
[7] "l_win_difference"   "l_WinStreak_dif"    "l_win"             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="http://localhost:5419/#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(rightSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "l_FullName"         "r_FullName"         "r_seniority"       
[4] "r_reach_dif_cm"     "r_w.l_ratio"        "r_total_fights_dif"
[7] "r_win_difference"   "r_WinStreak_dif"    "r_win"             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="http://localhost:5419/#cb84-1" aria-hidden="true" tabindex="-1"></a>leftNNW <span class="ot">&lt;-</span>leftSel[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span>
<span id="cb84-2"><a href="http://localhost:5419/#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(leftNNW)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "l_seniority"        "l_reach_dif_cm"     "l_w.l_ratio"       
[4] "l_total_fights_dif" "l_win_difference"   "l_WinStreak_dif"   
[7] "l_win"             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="http://localhost:5419/#cb86-1" aria-hidden="true" tabindex="-1"></a>rightNNW <span class="ot">&lt;-</span> rightSel[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span>
<span id="cb86-2"><a href="http://localhost:5419/#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(rightNNW)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "r_seniority"        "r_reach_dif_cm"     "r_w.l_ratio"       
[4] "r_total_fights_dif" "r_win_difference"   "r_WinStreak_dif"   
[7] "r_win"             </code></pre>
</div>
</div>
<p>Models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="http://localhost:5419/#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log models:</span></span>
<span id="cb88-2"><a href="http://localhost:5419/#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="http://localhost:5419/#cb88-3" aria-hidden="true" tabindex="-1"></a>leftLogRegNF <span class="ot">&lt;-</span> <span class="fu">glm</span>(l_win<span class="sc">~</span>l_seniority <span class="sc">+</span> <span class="fu">I</span>(l_w.l_ratio<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> l_reach_dif_cm <span class="sc">+</span> l_total_fights_dif <span class="sc">+</span> l_win_difference <span class="sc">+</span> l_WinStreak_dif, <span class="at">family=</span>binomial, <span class="at">data=</span>l_stat)</span>
<span id="cb88-4"><a href="http://localhost:5419/#cb88-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-5"><a href="http://localhost:5419/#cb88-5" aria-hidden="true" tabindex="-1"></a>rightLogRegNF <span class="ot">&lt;-</span> <span class="fu">glm</span>(r_win<span class="sc">~</span>r_seniority <span class="sc">+</span> r_w.l_ratio <span class="sc">+</span> r_reach_dif_cm <span class="sc">+</span> r_total_fights_dif <span class="sc">+</span> r_win_difference <span class="sc">+</span> r_WinStreak_dif, <span class="at">family=</span>binomial, <span class="at">data=</span>r_stat)  </span>
<span id="cb88-6"><a href="http://localhost:5419/#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="http://localhost:5419/#cb88-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Square transformation was not found significant in the right model</span></span>
<span id="cb88-8"><a href="http://localhost:5419/#cb88-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-9"><a href="http://localhost:5419/#cb88-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(leftLogRegNF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = l_win ~ l_seniority + I(l_w.l_ratio^2) + l_reach_dif_cm + 
    l_total_fights_dif + l_win_difference + l_WinStreak_dif, 
    family = binomial, data = l_stat)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         0.065408   0.029038   2.253   0.0243 *  
l_seniority        -0.039663   0.005216  -7.604 2.86e-14 ***
I(l_w.l_ratio^2)   -0.006270   0.001273  -4.926 8.41e-07 ***
l_reach_dif_cm      0.013983   0.003153   4.435 9.20e-06 ***
l_total_fights_dif  0.024213   0.001895  12.777  &lt; 2e-16 ***
l_win_difference    0.324288   0.016639  19.489  &lt; 2e-16 ***
l_WinStreak_dif     0.072744   0.016288   4.466 7.97e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9666.6  on 6972  degrees of freedom
Residual deviance: 8579.7  on 6966  degrees of freedom
  (211 observations deleted due to missingness)
AIC: 8593.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="http://localhost:5419/#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rightLogRegNF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = r_win ~ r_seniority + r_w.l_ratio + r_reach_dif_cm + 
    r_total_fights_dif + r_win_difference + r_WinStreak_dif, 
    family = binomial, data = r_stat)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        -0.109813   0.065588  -1.674   0.0941 .  
r_seniority        -0.040249   0.005204  -7.734 1.04e-14 ***
r_w.l_ratio         0.039361   0.021969   1.792   0.0732 .  
r_reach_dif_cm      0.013961   0.003147   4.436 9.17e-06 ***
r_total_fights_dif  0.024138   0.001890  12.773  &lt; 2e-16 ***
r_win_difference    0.264660   0.016668  15.879  &lt; 2e-16 ***
r_WinStreak_dif     0.073554   0.016291   4.515 6.33e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9666.6  on 6972  degrees of freedom
Residual deviance: 8594.9  on 6966  degrees of freedom
  (211 observations deleted due to missingness)
AIC: 8608.9

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="http://localhost:5419/#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PREDICTIONS</span></span>
<span id="cb92-2"><a href="http://localhost:5419/#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="http://localhost:5419/#cb92-3" aria-hidden="true" tabindex="-1"></a>leftProbNF <span class="ot">&lt;-</span> <span class="fu">predict</span>(leftLogRegNF,leftNNW,<span class="at">type=</span><span class="st">'response'</span>)</span>
<span id="cb92-4"><a href="http://localhost:5419/#cb92-4" aria-hidden="true" tabindex="-1"></a>leftPredNF <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(leftProbNF <span class="sc">&gt;</span> <span class="fl">0.7</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb92-5"><a href="http://localhost:5419/#cb92-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-6"><a href="http://localhost:5419/#cb92-6" aria-hidden="true" tabindex="-1"></a>leftTableNF <span class="ot">&lt;-</span> <span class="fu">table</span>(leftPredNF, leftNNW<span class="sc">$</span>l_win)</span>
<span id="cb92-7"><a href="http://localhost:5419/#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(leftPredNF, leftNNW<span class="sc">$</span>l_win)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
leftPredNF  0  1
         0 22 20
         1  1  7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="http://localhost:5419/#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(leftPredNF<span class="sc">==</span>leftNNW<span class="sc">$</span>l_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.58</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="http://localhost:5419/#cb96-1" aria-hidden="true" tabindex="-1"></a>leftPrecNF <span class="ot">&lt;-</span> (leftTableNF[<span class="dv">4</span>]<span class="sc">/</span>(leftTableNF[<span class="dv">4</span>]<span class="sc">+</span>leftTableNF[<span class="dv">2</span>])); leftPrecNF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.875</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="http://localhost:5419/#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right</span></span>
<span id="cb98-2"><a href="http://localhost:5419/#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="http://localhost:5419/#cb98-3" aria-hidden="true" tabindex="-1"></a>rightProbNF <span class="ot">&lt;-</span> <span class="fu">predict</span>(rightLogRegNF,rightNNW,<span class="at">type=</span><span class="st">'response'</span>)</span>
<span id="cb98-4"><a href="http://localhost:5419/#cb98-4" aria-hidden="true" tabindex="-1"></a>rightPredNF <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(rightProbNF <span class="sc">&gt;</span> <span class="fl">0.7</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb98-5"><a href="http://localhost:5419/#cb98-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-6"><a href="http://localhost:5419/#cb98-6" aria-hidden="true" tabindex="-1"></a>rightTableNF <span class="ot">&lt;-</span> <span class="fu">table</span>(rightPredNF, rightNNW<span class="sc">$</span>r_win)</span>
<span id="cb98-7"><a href="http://localhost:5419/#cb98-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(rightPredNF, rightNNW<span class="sc">$</span>r_win)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
rightPredNF  0  1
          0 23 15
          1  4  8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="http://localhost:5419/#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(rightPredNF<span class="sc">==</span>rightNNW<span class="sc">$</span>r_win)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.62</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="http://localhost:5419/#cb102-1" aria-hidden="true" tabindex="-1"></a>rightPrecNF <span class="ot">&lt;-</span> (rightTableNF[<span class="dv">4</span>]<span class="sc">/</span>(rightTableNF[<span class="dv">4</span>]<span class="sc">+</span>rightTableNF[<span class="dv">2</span>])); rightPrecNF </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6666667</code></pre>
</div>
</div>
<p>The left model shows a precision of 87.5% over the past month’s fights and the right model shows a precision of 67%. To combine these models, our thought process was that we would take the left model’s answer as the overall predicted winner if the right model didn’t know (predicted uncertain), or the right model’s answer if the left model didn’t know. They never predicted different winners. Either both would be uncertain or one model would know the answer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="http://localhost:5419/#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ADDING PREDICTIONS TO SELECTED LEFT AND RIGHT COLUMNS</span></span>
<span id="cb104-2"><a href="http://localhost:5419/#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="http://localhost:5419/#cb104-3" aria-hidden="true" tabindex="-1"></a>leftSel<span class="sc">$</span>predicted_l_win <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb104-4"><a href="http://localhost:5419/#cb104-4" aria-hidden="true" tabindex="-1"></a>  leftPredNF <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb104-5"><a href="http://localhost:5419/#cb104-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-6"><a href="http://localhost:5419/#cb104-6" aria-hidden="true" tabindex="-1"></a>rightSel<span class="sc">$</span>predicted_r_win <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb104-7"><a href="http://localhost:5419/#cb104-7" aria-hidden="true" tabindex="-1"></a>  rightPredNF <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Adding combined model results to the table for easier viewing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="http://localhost:5419/#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># RESULTS</span></span>
<span id="cb105-2"><a href="http://localhost:5419/#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="http://localhost:5419/#cb105-3" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> pastFights[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">35</span>,<span class="dv">36</span>)]</span>
<span id="cb105-4"><a href="http://localhost:5419/#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="http://localhost:5419/#cb105-5" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>left_predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb105-6"><a href="http://localhost:5419/#cb105-6" aria-hidden="true" tabindex="-1"></a>  leftSel<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb105-7"><a href="http://localhost:5419/#cb105-7" aria-hidden="true" tabindex="-1"></a>  leftSel<span class="sc">$</span>l_FullName, </span>
<span id="cb105-8"><a href="http://localhost:5419/#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Uncertain'</span></span>
<span id="cb105-9"><a href="http://localhost:5419/#cb105-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb105-10"><a href="http://localhost:5419/#cb105-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-11"><a href="http://localhost:5419/#cb105-11" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>right_predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb105-12"><a href="http://localhost:5419/#cb105-12" aria-hidden="true" tabindex="-1"></a>  rightSel<span class="sc">$</span>predicted_r_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb105-13"><a href="http://localhost:5419/#cb105-13" aria-hidden="true" tabindex="-1"></a>  rightSel<span class="sc">$</span>r_FullName, </span>
<span id="cb105-14"><a href="http://localhost:5419/#cb105-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Uncertain'</span></span>
<span id="cb105-15"><a href="http://localhost:5419/#cb105-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb105-16"><a href="http://localhost:5419/#cb105-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-17"><a href="http://localhost:5419/#cb105-17" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>overall_predicted_winner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb105-18"><a href="http://localhost:5419/#cb105-18" aria-hidden="true" tabindex="-1"></a>  leftSel<span class="sc">$</span>predicted_l_win <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb105-19"><a href="http://localhost:5419/#cb105-19" aria-hidden="true" tabindex="-1"></a>  leftSel<span class="sc">$</span>l_FullName, </span>
<span id="cb105-20"><a href="http://localhost:5419/#cb105-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(rightSel<span class="sc">$</span>predicted_r_win <span class="sc">==</span> <span class="dv">1</span>, rightSel<span class="sc">$</span>r_FullName, <span class="st">'Uncertain'</span>)</span>
<span id="cb105-21"><a href="http://localhost:5419/#cb105-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb105-22"><a href="http://localhost:5419/#cb105-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-23"><a href="http://localhost:5419/#cb105-23" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>accurate <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb105-24"><a href="http://localhost:5419/#cb105-24" aria-hidden="true" tabindex="-1"></a>  results<span class="sc">$</span>overall_predicted_winner <span class="sc">==</span> <span class="st">"Uncertain"</span>, </span>
<span id="cb105-25"><a href="http://localhost:5419/#cb105-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"uncertain"</span>,  <span class="co"># Both predictions were uncertain</span></span>
<span id="cb105-26"><a href="http://localhost:5419/#cb105-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(</span>
<span id="cb105-27"><a href="http://localhost:5419/#cb105-27" aria-hidden="true" tabindex="-1"></a>    (results<span class="sc">$</span>overall_predicted_winner <span class="sc">==</span> results<span class="sc">$</span>l_FullName <span class="sc">&amp;</span> results<span class="sc">$</span>l_win <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|</span> </span>
<span id="cb105-28"><a href="http://localhost:5419/#cb105-28" aria-hidden="true" tabindex="-1"></a>      (results<span class="sc">$</span>overall_predicted_winner <span class="sc">==</span> results<span class="sc">$</span>r_FullName <span class="sc">&amp;</span> results<span class="sc">$</span>r_win <span class="sc">==</span> <span class="dv">1</span>), </span>
<span id="cb105-29"><a href="http://localhost:5419/#cb105-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"accurate"</span>,  <span class="co"># Predicted winner matches the actual winner</span></span>
<span id="cb105-30"><a href="http://localhost:5419/#cb105-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">"inaccurate"</span> <span class="co"># Predicted winner does not match the actual winner</span></span>
<span id="cb105-31"><a href="http://localhost:5419/#cb105-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb105-32"><a href="http://localhost:5419/#cb105-32" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gauging combined conservative model precision:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="http://localhost:5419/#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ACCURACIES</span></span>
<span id="cb106-2"><a href="http://localhost:5419/#cb106-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-3"><a href="http://localhost:5419/#cb106-3" aria-hidden="true" tabindex="-1"></a>accuracy_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(results<span class="sc">$</span>accurate)</span>
<span id="cb106-4"><a href="http://localhost:5419/#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(accuracy_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  accurate inaccurate  uncertain 
        15          5         30 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="http://localhost:5419/#cb108-1" aria-hidden="true" tabindex="-1"></a>precise <span class="ot">&lt;-</span> accuracy_counts[<span class="dv">1</span>]<span class="sc">/</span>(accuracy_counts[<span class="dv">1</span>]<span class="sc">+</span>accuracy_counts[<span class="dv">2</span>])</span>
<span id="cb108-2"><a href="http://localhost:5419/#cb108-2" aria-hidden="true" tabindex="-1"></a>precise</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>accurate 
    0.75 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="http://localhost:5419/#cb110-1" aria-hidden="true" tabindex="-1"></a>dec7accuracy <span class="ot">&lt;-</span> <span class="fu">table</span>(results<span class="sc">$</span>accurate[<span class="dv">26</span><span class="sc">:</span><span class="dv">39</span>])</span>
<span id="cb110-2"><a href="http://localhost:5419/#cb110-2" aria-hidden="true" tabindex="-1"></a>dec7accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 accurate uncertain 
        4        10 </code></pre>
</div>
</div>
<p>The first number 0.75, shows that this new approach correctly predicted winners 75% of the time over the last month. The second output showing 4 accurate and 10 uncertain means that it had an 100% precision on December 7th. We wish we would’ve used this model!</p>
</section>
</section>
<section id="continuing-notes" class="level1">
<h1>Continuing Notes</h1>
<p>We are continuing to work on this model, areas of interest being web scraping more predictor columns from the UFC stats page. For example, scraping pages like this: <a href="http://ufcstats.com/fighter-details/15df64c02b6b0fde">Link</a>.</p>
<p>Variables of interest here would be career statistics SLpM, Str. Acc., etc.</p>
<p>A loss streak variable similar to our win streak variable could also improve the models.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->





<script>window.backupDefine = window.define; window.define = undefined;</script>
<script type="text/javascript" src="./ufcproj_files/quarto-preview.js.download"></script>
<script>window.define = window.backupDefine; window.backupDefine = undefined;</script>
<script type="text/javascript">
  const options = {
    origin: "",
    search: "",
    inputFile: "C:\Users\lucas\Desktop\MLfall\ufc\ufcproj.qmd",
    isPresentation: false
  }
  document.addEventListener("DOMContentLoaded", function () {
    window.QuartoPreview.init(options);
  });
</script>
</body></html>